import { NextResponse } from 'next/server'
import { createClient } from '@/utils/supabase/server'

export async function GET(request: Request) {
  const { searchParams, origin } = new URL(request.url)
  const code = searchParams.get('code')

  if (code) {
    const supabase = await createClient()
    const { error } = await supabase.auth.exchangeCodeForSession(code)

    if (!error) {
      // 1. Get the authenticated user
      const { data: { user } } = await supabase.auth.getUser()

      if (user) {
        // A. Determine Provider & Uni Status
        const provider = user.app_metadata?.provider || 'unknown'
        const authProvider = provider === 'azure' ? 'microsoft' : provider

        // CHECK: Is this a Manipal Email?
        const isManipal = user.email?.endsWith('@learner.manipal.edu') || false

        // 2. Fetch Profile to see if they exist
        const { data: profile } = await supabase
          .from('profiles')
          .select('full_name, mobile_number, is_university_student')
          .eq('id', user.id)
          .single()

        // 3. If New User -> Insert Logic
        if (!profile) {
          // LOGIC: Only auto-fill name for Microsoft. Google users must type it.
          let initialName = null
          if (authProvider === 'microsoft') {
            initialName = user.user_metadata?.full_name || user.user_metadata?.name || null
          }

          // Insert the base row. 
          // Note: We leave mobile_number NULL. This is the flag that forces onboarding.
          // Note: solstice_id is auto-generated by your DB trigger.
          const { error: insertError } = await supabase.from('profiles').insert({
            id: user.id,
            email: user.email,
            auth_provider: authProvider,
            is_university_student: isManipal,
            full_name: initialName,
          })

          if (insertError) console.error('Profile creation failed:', insertError)
        }

        // 4. Re-fetch profile to check status (in case of race conditions or just updated)
        const { data: currentProfile } = await supabase
          .from('profiles')
          .select('full_name, mobile_number')
          .eq('id', user.id)
          .single()

        // 5. THE GATEKEEPER LOGIC

        // If they don't have a Mobile Number OR a Name, they haven't finished onboarding.
        // (Even if MS gave them a name, they still need to add a phone number).
        if (!currentProfile?.mobile_number || !currentProfile?.full_name) {
          return NextResponse.redirect(`${origin}/complete-profile`)
        }

        // 6. Success -> Go to Profile (admins can navigate to dashboard from there)
        return NextResponse.redirect(`${origin}/profile`)
      }
    }
  }

  // If something broke
  return NextResponse.redirect(`${origin}/login?error=true`)
}